name: Neoload Test Execution
on:
  workflow_dispatch: # Allows manual trigger
jobs:
  run-neoload-test:
    runs-on: neoload # Matches dxpvr-perfTest runner
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Execute NeoLoad Scenario
        shell: powershell
        run: |
          $neoloadPath = 'C:\Program Files\NeoLoad 2024.3\bin\NeoLoadCmd.exe'
          $projectPath = "$(env:GITHUB_WORKSPACE)\petstore.nlp"
          & $neoloadPath -project $projectPath -launch "scenario1" -noGUI
