name: Neoload Test Execution
on:
  workflow_dispatch: # Allows manual trigger
jobs:
  run-neoload-test:
    runs-on: neoload-runner-2 # Matches dxpvr-perfTest runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to NeoLoad
        env:
          NL_TOKEN: ${{ secrets.NEOLOAD_TOKEN }}
        run: |
          neoload login --token $NL_TOKEN
      - name: Execute NeoLoad Scenario
        run: |
          neoload run --project "petstore.nlp" --scenario "scenario1"
         
